name: squeeze_pix
description: "An App To Compress Large and Bulky Images and Share Instanly."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  image_picker: ^1.2.1
  path_provider: ^2.1.5 # Add this line
  path: ^1.9.1 # Add this line
  share_plus: ^12.0.1
  flutter_image_compress: ^2.4.0
  flutter_staggered_animations: ^1.1.1
  open_filex: ^4.7.0
  archive: ^4.0.7
  unity_ads_plugin: ^0.3.28
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0
  before_after: ^3.2.0
  file_picker: ^10.3.6
  file_saver: ^0.3.1
  saf_stream: ^0.12.3
  permission_handler: ^12.0.1
  google_fonts: ^6.3.2
  in_app_purchase: ^3.2.3
  shimmer: ^3.0.0
  image_cropper: ^11.0.0
  gal: ^2.3.2
  pdf: ^3.11.3
  flutter_colorpicker: ^1.1.0
  image: ^4.5.4
  http: ^1.6.0
  # flutter_document_picker: ^5.4.1
  # google_mobile_ads: ^6.0.0
  # open_file_plus: ^3.4.1+1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sq_pix_logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/sq_pix_logo.png
    - assets/templates/
  #   - images/a_dot_ham.jpeg

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
